# Generated by Django 4.2.2 on 2023-06-29 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # add states (Prêt à dev, Dev en cours, Review, Recette interne, Recette client, Go prod, Terminé)
        migrations.RunSQL(
            """
            INSERT INTO api_state (name, createdAt) VALUES ('Prêt à dev', '2023-06-29 00:00:00');
            INSERT INTO api_state (name, createdAt) VALUES ('Dev en cours', '2023-06-29 00:00:00');
            INSERT INTO api_state (name, createdAt) VALUES ('Review', '2023-06-29 00:00:00');
            INSERT INTO api_state (name, createdAt) VALUES ('Recette interne', '2023-06-29 00:00:00');
            INSERT INTO api_state (name, createdAt) VALUES ('Recette client', '2023-06-29 00:00:00');
            INSERT INTO api_state (name, createdAt) VALUES ('Go prod', '2023-06-29 00:00:00');
            INSERT INTO api_state (name, createdAt) VALUES ('Terminé', '2023-06-29 00:00:00');
            """
        ),
    ]
